version: 2
updates:
- package-ecosystem: gradle
  directory: "/sdk-dependency-versions"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/gradle/plugins"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
