language: java

jdk:
    - openjdk8
    - openjdk11

script:
    - echo $TRAVIS_JDK_VERSION
    - export MVN_PROFILES=$([ "$TRAVIS_JDK_VERSION" = "openjdk11" ] && echo '-P errorprone')
    # errorprone only works on JDK 9 and above
    - mvn $MVN_PROFILES checkstyle:check spotbugs:check compile test
    - (cd examples && mvn $MVN_PROFILES checkstyle:check spotbugs:check compile)
    - (cd android-example && ./gradlew clean build)
