version: "3"

silent: true

tasks:
    default:
        deps:
            - build

    docs:
        cmds:
            - ./gradlew javadoc

    build:
        cmds:
            - ./gradlew compileJava {{.CLI_ARGS}}
    clean:
        cmds:
            - ./gradlew clean

    format:
    lint:

    package:
        cmds:
            - ./gradlew sdk:assemble
    test:
        deps:
            - "test:unit"
            - "test:integration"

    "test:unit":
        cmds:
            - ./gradlew test {{.CLI_ARGS}}

    "test:integration":
        cmds:
            - ./gradlew -POPERATOR_KEY=$OPERATOR_KEY -POPERATOR_ID=$OPERATOR_ID -PCONFIG_FILE=$CONFIG_FILE integrationTest {{.CLI_ARGS}}

    "update:snapshots":
        cmds:
            - rm sdk/src/test/java/com/hedera/hashgraph/sdk/*.snap
            - ./gradlew clean test

    "update:proto":
        cmds:
            - ./scripts/update_protobufs.py main

    "update:addressbooks:mainnet":
        cmds:
            - ./gradlew runGetAddressBook
            - mv examples/address-book.proto.bin sdk/src/main/resources/addressbook/mainnet.pb
        env:
            HEDERA_NETWORK: mainnet

    "update:addressbooks:testnet":
        cmds:
            - ./gradlew runGetAddressBook
            - mv examples/address-book.proto.bin sdk/src/main/resources/addressbook/testnet.pb
        env:
            HEDERA_NETWORK: testnet

    "update:addressbooks:previewnet":
        cmds:
            - ./gradlew runGetAddressBook
            - mv examples/address-book.proto.bin sdk/src/main/resources/addressbook/previewnet.pb
        env:
            HEDERA_NETWORK: previewnet

    "update:addressbooks":
        cmds:
            - task: "update:addressbooks:mainnet"
            - task: "update:addressbooks:testnet"
            - task: "update:addressbooks:previewnet"

    update:
        cmds:
            - task: "update:proto"
            - task: "update:snapshots"
            - task: "update:addressbooks"

    publish:
        env:
            FILES: "sdk/src/main/java/com/hedera/hashgraph/sdk/*.java executable-processor/src/main/java/com/hedera/hashgraph/sdk/*.java"
        preconditions:
            - git diff-index --quiet HEAD
        cmds:
            - git clean -ffdx
            - ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
            - perl -p -i -e "s#sdk-jdk7\.gradle#sdk.gradle#g" sdk/build.gradle
            - git clean -ffdx
            - rm -f sdk/src/main/java/com/hedera/hashgraph/sdk/FutureConverter.java
            - perl -p -i -e "s#java8#java#g" $FILES
            - perl -p -i -e "s#org\.threeten\.bp#java.time#g" $FILES
            - perl -p -i -e "s#J8Arrays#Arrays#g" $FILES
            - perl -p -i -e "s#IntStreams#IntStream#g" $FILES
            - perl -p -i -e "s#\bLists\b#List#g" $FILES
            - perl -p -i -e "s#StreamSupport\.stream\((.*)\).map#\1.stream().map#g" $FILES
            - perl -p -i -e "s#import static com.hedera.hashgraph.sdk.FutureConverter.toCompletableFuture;#import net.javacrumbs.futureconverter.guavacommon.GuavaFutureUtils;\nimport net.javacrumbs.futureconverter.java8common.Java8FutureUtils;#g" $FILES
            - perl -p -i -e "s#toCompletableFuture\((.*)\).handle#Java8FutureUtils.createCompletableFuture(GuavaFutureUtils.createValueSource(\1)).handle#g" $FILES
            - ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
            - perl -p -i -e "s#sdk\.gradle#sdk-full.gradle#g" sdk/build.gradle
            - git clean -ffdx
            - ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
            - git restore sdk executable-processor
