version: "3"

silent: true

tasks:
    default:
        deps:
            - build

    docs:
        cmds:
            - ./gradlew javadoc

    build:
        cmds:
            - ./gradlew compileJava {{.CLI_ARGS}}
    clean:
        cmds:
            - ./gradlew clean

    package:
        cmds:
            - ./gradlew sdk:assemble
    test:
        deps:
            - "test:unit"
            - "test:integration"

    "test:unit":
        cmds:
            - ./gradlew test {{.CLI_ARGS}}

    "test:integration":
        cmds:
            - ./gradlew -POPERATOR_ID=$OPERATOR_ID -POPERATOR_KEY=$OPERATOR_KEY -PHEDERA_NETWORK=$HEDERA_NETWORK integrationTest {{.CLI_ARGS}}
        env:
            OPERATOR_KEY: '0xa608e2130a0a3cb34f86e757303c862bee353d9ab77ba4387ec084f881d420d4'
            OPERATOR_ID: '0.0.1022'
            HEDERA_NETWORK: 'localhost'

    "update:snapshots":
        cmds:
            - rm sdk/src/test/java/com/hedera/hashgraph/sdk/*.snap
            - ./gradlew clean test

    "update:proto":
        cmds:
            - ./scripts/update_protobufs.py main

    "update:addressbooks:mainnet":
        cmds:
            - ./gradlew runGetAddressBook
            - mv examples/address-book.proto.bin sdk/src/main/resources/addressbook/mainnet.pb
        env:
            HEDERA_NETWORK: mainnet

    "update:addressbooks:testnet":
        cmds:
            - ./gradlew runGetAddressBook
            - mv examples/address-book.proto.bin sdk/src/main/resources/addressbook/testnet.pb
        env:
            HEDERA_NETWORK: testnet

    "update:addressbooks:previewnet":
        cmds:
            - ./gradlew runGetAddressBook
            - mv examples/address-book.proto.bin sdk/src/main/resources/addressbook/previewnet.pb
        env:
            HEDERA_NETWORK: previewnet

    "update:addressbooks":
        cmds:
            -   task: "update:addressbooks:mainnet"
            -   task: "update:addressbooks:testnet"
            -   task: "update:addressbooks:previewnet"

    update:
        cmds:
            -   task: "update:proto"
            -   task: "update:snapshots"
            -   task: "update:addressbooks"
