package com.hedera.hashgraph.sdk.crypto.ed25519;

import com.hedera.hashgraph.sdk.crypto.BadKeyException;
import com.hedera.hashgraph.sdk.crypto.Mnemonic;

import org.bouncycastle.math.ec.rfc8032.Ed25519;
import org.bouncycastle.util.encoders.Hex;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import org.junit.jupiter.params.provider.ValueSource;

import java.io.IOException;
import java.io.StringReader;
import java.io.StringWriter;
import java.nio.charset.StandardCharsets;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class Ed25519PrivateKeyTest {

    private static final String testKeyStr = "302e020100300506032b657004220420db484b828e64b2d8f12ce3c0a0e93a0b8cce7af1bb8f39c97732394482538e10";
    private static final String testKeyPem = "-----BEGIN PRIVATE KEY-----\n"
        + "MC4CAQAwBQYDK2VwBCIEINtIS4KOZLLY8SzjwKDpOguMznrxu485yXcyOUSCU44Q\n"
        + "-----END PRIVATE KEY-----\n";

    // generated by hedera-sdk-js, not used anywhere
    private static final String mnemonicString = "inmate flip alley wear offer often piece magnet surge toddler submit right radio absent pear floor belt raven price stove replace reduce plate home";
    private static final String mnemonicPrivateKey = "302e020100300506032b657004220420853f15aecd22706b105da1d709b4ac05b4906170c2b9c7495dff9af49e1391da";

    // backup phrase generated by the iOS wallet, not used anywhere
    private static final String iosMnemonicString ="tiny denial casual grass skull spare awkward indoor ethics dash enough flavor good daughter early hard rug staff capable swallow raise flavor empty angle";

    // private key for "default account", should be index 0
    private static final String iosDefaultPrivateKey ="5f66a51931e8c99089472e0d70516b6272b94dd772b967f8221e1077f966dbda2b60cf7ee8cf10ecd5a076bffad9a7c7b97df370ad758c0f1dd4ef738e04ceb6";

    // backup phrase generated by the Android wallet, also not used anywhere
    private static final String androidMnemonicString = "ramp april job flavor surround pyramid fish sea good know blame gate village viable include mixed term draft among monitor swear swing novel track";
    // private key for "default account", should be index 0
    private static final String androidDefaultPrivateKey = "c284c25b3a1458b59423bc289e83703b125c8eefec4d5aa1b393c2beb9f2bae66188a344ba75c43918ab12fa2ea4a92960eca029a2320d8c6a1c3b94e06c9985";

    private static final String pemPassphrase = "this is a passphrase";

    /*
        # enter passphrase "this is a passphrase"
        echo '302e020100300506032b657004220420db484b828e64b2d8f12ce3c0a0e93a0b8cce7af1bb8f39c97732394482538e10' \
        | xxd -r -p \
        | openssl pkey -inform der -aes-128-cbc
     */
    private static final String encryptedPem = "-----BEGIN ENCRYPTED PRIVATE KEY-----\n"
        + "MIGbMFcGCSqGSIb3DQEFDTBKMCkGCSqGSIb3DQEFDDAcBAi8WY7Gy2tThQICCAAw\n"
        + "DAYIKoZIhvcNAgkFADAdBglghkgBZQMEAQIEEOq46NPss58chbjUn20NoK0EQG1x\n"
        + "R88hIXcWDOECttPTNlMXWJt7Wufm1YwBibrxmCq1QykIyTYhy1TZMyxyPxlYW6aV\n"
        + "9hlo4YEh3uEaCmfJzWM=\n"
        + "-----END ENCRYPTED PRIVATE KEY-----\n";

    @Test
    @DisplayName("private key generates successfully")
    void keyGenerates() {
        final Ed25519PrivateKey key = Ed25519PrivateKey.generate();

        assertNotNull(key);
        assertNotNull(key.toBytes());
        // we generate the chain code at the same time
        assertTrue(key.supportsDerivation(), "generated key must support generation");
    }

    @Test
    @DisplayName("private key can be recovered from bytes")
    void keySerialization() {
        final Ed25519PrivateKey key1 = Ed25519PrivateKey.generate();
        final byte[] key1Bytes = key1.toBytes();
        final Ed25519PrivateKey key2 = Ed25519PrivateKey.fromBytes(key1Bytes);
        final byte[] key2Bytes = key2.toBytes();

        assertArrayEquals(key1Bytes, key2Bytes);
    }

    @ParameterizedTest
    @DisplayName("private key can be recovered from external string")
    @ValueSource(strings = {
        "302e020100300506032b657004220420db484b828e64b2d8f12ce3c0a0e93a0b8cce7af1bb8f39c97732394482538e10",
        // raw hex (concatenated private + public key)
        "db484b828e64b2d8f12ce3c0a0e93a0b8cce7af1bb8f39c97732394482538e10" +
            "e0c8ec2758a5879ffac226a13c0c516b799e72e35141a0dd828f94d37988a4b7",
        // raw hex (just private key)
        "db484b828e64b2d8f12ce3c0a0e93a0b8cce7af1bb8f39c97732394482538e10"
    })
    void externalKeyDeserialize(String keyStr) {
        final Ed25519PrivateKey key = Ed25519PrivateKey.fromString(keyStr);
        assertNotNull(key);
        // the above are all the same key
        assertEquals(
            testKeyStr,
            key.toString()
        );
    }

    @Test
    @DisplayName("private key can be encoded to a string")
    void keyToString() {
        final Ed25519PrivateKey key = Ed25519PrivateKey.fromString(testKeyStr);

        assertNotNull(key);
        assertEquals(testKeyStr, key.toString());
    }

    @Test
    @DisplayName("private key can be decoded from a PEM file")
    void keyFromPem() throws IOException {
        final StringReader stringReader = new StringReader(testKeyPem);
        final Ed25519PrivateKey privateKey = Ed25519PrivateKey.fromPem(stringReader);

        assertEquals(privateKey.toString(), testKeyStr);
    }

    @Test
    @DisplayName("private key can be decoded from a PEM file")
    void keyToPem() throws IOException {
        final StringWriter stringWriter = new StringWriter();
        final Ed25519PrivateKey privateKey = Ed25519PrivateKey.fromString(testKeyStr);
        privateKey.writePem(stringWriter);

        assertEquals(stringWriter.toString(), testKeyPem);
    }

    @Test
    @DisplayName("private key can be recovered from a mnemonic")
    void keyFromMnemonic() {
        final Mnemonic mnemonic = Mnemonic.fromString(mnemonicString);
        final Ed25519PrivateKey key = Ed25519PrivateKey.fromMnemonic(mnemonic);
        final Ed25519PrivateKey key2 = Ed25519PrivateKey.fromString(mnemonicPrivateKey);
        assertArrayEquals(key2.toBytes(), key.toBytes());
    }

    @Test
    @DisplayName("derived key matches that of the mobile wallets")
    void deriveKeyIndex0() {
        final Mnemonic iosMnemonic = Mnemonic.fromString(iosMnemonicString);
        final Ed25519PrivateKey iosKey = Ed25519PrivateKey.fromMnemonic(iosMnemonic);

        final Ed25519PrivateKey iosDerivedKey = iosKey.derive(0);
        final Ed25519PrivateKey iosExpectedKey = Ed25519PrivateKey.fromString(iosDefaultPrivateKey);

        assertArrayEquals(iosDerivedKey.toBytes(), iosExpectedKey.toBytes());

        final Mnemonic androidMnemonic = Mnemonic.fromString(androidMnemonicString);
        final Ed25519PrivateKey androidKey = Ed25519PrivateKey.fromMnemonic(androidMnemonic);

        final Ed25519PrivateKey androidDerivedKey = androidKey.derive(0);
        final Ed25519PrivateKey androidExpectedKey = Ed25519PrivateKey.fromString(androidDefaultPrivateKey);

        assertArrayEquals(androidDerivedKey.toBytes(), androidExpectedKey.toBytes());
    }

    @Test
    @DisplayName("generated mnemonic can be turned into a working private key")
    void keyFromGeneratedMnemonic() {
        final Mnemonic mnemonic = Mnemonic.generate();
        final Ed25519PrivateKey privateKey = Ed25519PrivateKey.fromMnemonic(mnemonic);

        final byte[] messageToSign = "this is a test message".getBytes(StandardCharsets.UTF_8);

        final byte[] signature = privateKey.sign(messageToSign);

        assertTrue(Ed25519.verify(signature, 0, privateKey.publicKey.toBytes(), 0, messageToSign, 0, messageToSign.length));
    }
/*
    // punting on encrypted PEM generation for now; see PemUtils for reason
    @Test
    @DisplayName("toEncryptedPem/fromEncryptedPem are inverses")
    void keyToEncryptedPemAndBack() throws IOException {
        Ed25519PrivateKey privateKey = Ed25519PrivateKey.fromString(testKeyStr);

        StringWriter writer = new StringWriter();
        privateKey.writePem(writer, pemPassphrase);

        String encodedPem = writer.toString();
        StringReader reader = new StringReader(encodedPem);

        Ed25519PrivateKey fromPem = Ed25519PrivateKey.readPem(reader, pemPassphrase);

        assertArrayEquals(privateKey.toBytes(), fromPem.toBytes());
    }
*/

    @Test
    @DisplayName("fromPem() with passphrase produces same key")
    void keyFromEncryptedPem() throws IOException {
        Ed25519PrivateKey privateKey = Ed25519PrivateKey.fromPem(encryptedPem, pemPassphrase);
        assertEquals(privateKey.toString(), testKeyStr);
    }

    @Test
    @DisplayName("fromPem() with encrypted key without a passphrase throws useful error")
    void errorKeyFromEncryptedPemNoPassphrase() {
        assertEquals(
            "PEM file contained an encrypted private key but no passphrase was given",
            assertThrows(BadKeyException.class, () -> Ed25519PrivateKey.fromPem(encryptedPem)).getMessage());
    }

    private static final String messageStr = "This is a message about the world.";
    private static final byte[] messageBytes = messageStr.getBytes(StandardCharsets.UTF_8);
    private static final String sigStr = "73bea53f31ca9c42a422ecb7516ec08d0bbd1a6bfd630ccf10ec1872454814d29f4a8011129cd007eab544af01a75f508285b591e5bed24b68f927751e49e30e";

    @SuppressWarnings("unused")
    private static Stream<String> privKeyStrings() {
        return Stream.of(
            "302e020100300506032b657004220420db484b828e64b2d8f12ce3c0a0e93a0b8cce7af1bb8f39c97732394482538e10",
            // raw hex (concatenated private + public key)
            "db484b828e64b2d8f12ce3c0a0e93a0b8cce7af1bb8f39c97732394482538e10" +
                "e0c8ec2758a5879ffac226a13c0c516b799e72e35141a0dd828f94d37988a4b7",
            // raw hex (just private key)
            "db484b828e64b2d8f12ce3c0a0e93a0b8cce7af1bb8f39c97732394482538e10"
        );
    }

    @ParameterizedTest
    @DisplayName("reproducible signature can be computed")
    @MethodSource("privKeyStrings")
    void reproducibleSignature(String keyStr) {
        final Ed25519PrivateKey key = Ed25519PrivateKey.fromString(keyStr);
        final byte[] signature = key.sign(messageBytes);

        assertEquals(
            sigStr,
            Hex.toHexString(signature)
        );
    }
}
