name: Java

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build
      run: mvn -B package --file pom.xml

  check:
    name: Checkstyle
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-checkstyle-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-checkstyle-

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Checkstyle
      run: mvn -B checkstyle:check

  android-build:
    name: Test SDK and Build Android Example
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # cache Maven artifacts for building the SDK
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-build-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-build-

    # Cache Gradle artifacts for building the android-example
    - uses: actions/cache@v1
      with:
        path: ${{ env.GRADLE_HOME }}/caches/build-cache-*
        key: ${{ runner.os }}-gradle-build-${{ hashFiles('**/build.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-build-

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: install SDK
      run: mvn install # implicitly runs tests
      # TODO: turn on `integration-testing` profile when we have testnet account for CI

    - name: Build Android Example
      working-directory: android-example
      run: gradle build
